### PR TITLE
Fixing import in unit tests

### PR DESCRIPTION
**Pull request by Lucas-C**
Fix error: `AttributeError: module 'multi_neighbors' has no attribute 'neighbors'`

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi @davidlesieur. Any chance you could review and merge this PR?

**Comment by davidlesieur** [comment]
Will do soon. Sorry for the delay!

**Comment by davidlesieur** [comment]
I had merged the PR, but then had a second thought... So I have modified `__init__.py` to automatically import all names from the module. This eases running the tests either from the plugins directory or directly from the module's directory. Please let me know if you encounter issues with this.

**Comment by Lucas-C** [comment]
Perfect, thanks !

**Pull request merged**
